version: '3.2'
services:
  redis:
    container_name: redis
    image: redis:alpine3.16
    ports:
      - 6379:6379
    hostname: "redis"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  spotifyplaylistshuffler:
    container_name: spotifyplaylistshuffler
    image: spotifyplaylistshuffler
    ports:
      - 8888:8888
    hostname: "spotifyplaylistshuffler"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - type: bind
        source: "."
        target: /app
    depends_on: ["redis"]